### ISSUE TITLE
<center> is not reccomended

### ISSUE THREAD

**Issue by GrahamSH-LLK** [OfficeBlock/officeblock.github.io#3]

**Comment by GrahamSH-LLK** [comment]
I think it's deprecated

**Comment by ghost** [comment]
> I think it's deprecated

@GrahamSH-LLK uhh no, it works fine on other websites i make that use it

**Comment by GrahamSH-LLK** [comment]
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/center

**Comment by TheTort** [comment]
that means it's not supported on firefox

**Comment by GrahamSH-LLK** [comment]
> that means it's not supported on firefox

No it doesn't. It's "obsolete", but still _works_ cause browsers don't wanna break sites.

**Comment by TheTort** [comment]
oh

**Comment by TheTort** [comment]
i just imagine people wondering what were talking about after the new site comes out

**Comment by ghost** [comment]
> https://developer.mozilla.org/en-US/docs/Web/HTML/Element/center

@GrahamSH-LLK oh, idk then
